### PR TITLE
task/improve-authentication

### LINKED ISSUE #12: task/improve-authenication
Logo di  bagian login kurang ke bawah 
belum ada flash data success ketika after register success redirect to login
fix logic login between user and pemilik bengkel use same email
fix logic register between user and pemilik bengkel use same email
errors authentication(login) put on pop up

### PR DESCRIPTION
**Pull request by deepDeployCode**
- fix auth register for ower and users
- fix custom validation for validate request auth owner and users
- fix view user register and owner register

### CODE REVIEW

**Review by kamilanawa — APPROVED** [review]
sorry ya mas , aku review dulu ,

**Review by deepDeployCode — COMMENTED** [review]
@kamilanawa di review bae2 mbak jangan asal approve yah, pastikan sudah running sesuai end to end baru di approve mbak, tp kalo tidak sesuai end to end berarti revisi gitu.

**Comment by deepDeployCode** [comment]
@kamilanawa jadi cara reviewnya
1. fetch change terbaru
2. checkout branch
3. pull change of branch
4. run branch

**Review by kamilanawa — CHANGES_REQUESTED** [review]
@deepDeployCode fix it:
fix logic login between user and pemilik bengkel use same email
fix logic register between user and pemilik bengkel use same email
errors authentication(login) put on pop up

**Comment by deepDeployCode** [comment]
@kamilanawa sudah fix yah mbak

**Review by kamilanawa — APPROVED** [review]
@syamsulapp udah sesuai mas , terimakasih

**Review by xamppsul — APPROVED** [review]
@deepDeployCode good job

**Pull request merged**
